package com.contentpipeline.pipeline.handler;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The record itself is generated by the compiler; the only behaviour worth pinning
 * down is the two factory methods, which encode the success/failure invariants.
 */
class StepResultTest {

    @Test
    @DisplayName("success() flags success, keeps the artifacts, leaves error null")
    void successFactory() {
        UUID scriptId = UUID.randomUUID();

        StepResult result = StepResult.success(Map.of("script", scriptId));

        assertThat(result.success()).isTrue();
        assertThat(result.outputArtifactIds()).containsExactlyEntriesOf(Map.of("script", scriptId));
        assertThat(result.errorMessage()).isNull();
    }

    @Test
    @DisplayName("failure() flags failure, carries the message, has no artifacts")
    void failureFactory() {
        StepResult result = StepResult.failure("Claude call timed out");

        assertThat(result.success()).isFalse();
        assertThat(result.errorMessage()).isEqualTo("Claude call timed out");
        assertThat(result.outputArtifactIds()).isEmpty();
    }
}
